#!/bin/sh -e

if [ -z "${WALLET_ADDRESS}" ]; then
	echo "!!! WALLET_ADDRESS must be set to an ERC20 wallet address";
	exit 1;
fi;

if [ -n "${DAEMONADDRESS}" ]; then
  sed -i "s/127\.0\.0\.1/${DAEMONADDRESS}/" /usr/lib/node_modules/storjshare-daemon/lib/config/daemon.js
fi

# If our hostname has a hyphen-delimited suffix with a unique identifier, e.g. the ordinal if
#    we're in a Kubernetes statefulset, use that suffix as a subdirectry in the main DATADIR
if [ "$(echo "${USE_HOSTNAME_SUFFIX}" | tr /a-z/ /A-Z/)" == 'TRUE' ]; then
	DATADIR="${DATADIR}/$(hostname | rev | cut -d- -f1 | rev)";
fi;

storjshare daemon -F &
sleep 1;

mkdir -pv "${DATADIR}/share" "${DATADIR}/log";
if [ ! -f "${DATADIR}/config.json" ]; then
	storjshare create --storj "${WALLET_ADDRESS}" --storage "${DATADIR}/share" --size "${SHARE_SIZE}" --rpcport "${RPCPORT}" --rpcaddress "${RPCADDRESS}" --tunnelportmin 4001 --tunnelportmax 4003 --logdir "${DATADIR}/log" --outfile "${DATADIR}/config.json" --noedit;
fi;

storjshare start --config "${DATADIR}/config.json";

if [ -n "${STORJ_MONITOR_API_KEY}" ]; then
	sed -i "s/YOUR-TOKEN-HERE/${STORJ_MONITOR_API_KEY}/" /opt/StorjMonitor/storjMonitor.js;
	cd /opt/StorjMonitor;
	(/opt/StorjMonitor/storjMonitor.sh &) &
fi

wait;
