version: 2
jobs:
  build:
    docker:
      - image: koalaman/shellcheck-alpine:stable
    steps:
      - checkout
      - run:
          name: Check shell scripts
          command: |
            find . -name .git -prune -o -name '*.sh' -print -o \( -type f -and -perm -100 \) -print | wc -l
            find . -name .git -prune -o -name '*.sh' -print -o \( -type f -and -perm -100 \) -print | xargs shellcheck --external-sources
